
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS nome_social text,
  ADD COLUMN IF NOT EXISTS nome_fantasia text,
  ADD COLUMN IF NOT EXISTS categoria_inscricao text,
  ADD COLUMN IF NOT EXISTS concorre_cotas boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS cota_tipo text,
  ADD COLUMN IF NOT EXISTS funcao_profissao text,
  ADD COLUMN IF NOT EXISTS representa_coletivo boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS ano_criacao_coletivo text,
  ADD COLUMN IF NOT EXISTS qtd_pessoas_coletivo text,
  ADD COLUMN IF NOT EXISTS perfil_publico text,
  ADD COLUMN IF NOT EXISTS acao_cultural_publico text[],
  ADD COLUMN IF NOT EXISTS acessibilidade_arquitetonica text[],
  ADD COLUMN IF NOT EXISTS acessibilidade_comunicacional text[],
  ADD COLUMN IF NOT EXISTS acessibilidade_atitudinal text[],
  ADD COLUMN IF NOT EXISTS locais_execucao text,
  ADD COLUMN IF NOT EXISTS membros_coletivo jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS trajetoria_acoes text,
  ADD COLUMN IF NOT EXISTS trajetoria_inicio text,
  ADD COLUMN IF NOT EXISTS trajetoria_impacto text,
  ADD COLUMN IF NOT EXISTS trajetoria_outras_areas text,
  ADD COLUMN IF NOT EXISTS num_representantes_legais text,
  ADD COLUMN IF NOT EXISTS lgbtqiapn_tipo text,
  ADD COLUMN IF NOT EXISTS testemunha_nome text,
  ADD COLUMN IF NOT EXISTS testemunha_cpf text,
  ADD COLUMN IF NOT EXISTS testemunha_rg text,
  ADD COLUMN IF NOT EXISTS testemunha_telefone text,
  ADD COLUMN IF NOT EXISTS testemunha_endereco text;
